/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountDownTimer: typeof import('./components/CountDownTimer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LocationSection: typeof import('./components/LocationSection.vue')['default']
    NavButton: typeof import('./components/NavButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./components/Timeline.vue')['default']
  }
}
